---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  selector:
    app: spc
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deploy
  annotations:
    kubernetes.io/change-cause: "Spring-pet-clinic Deploymennt"
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: spc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spc
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: sujatajoshi/spc
          ports:
            - containerPort: 8080
